channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=24.2
- pip:
  - mlflow==2.14.3
  - cffi==1.17.0
  - cloudpickle==3.0.0
  - colorama==0.4.6
  - graphviz==0.20.3
  - imbalanced-learn==0.12.3
  - ipywidgets==8.1.3
  - lightgbm==4.5.0
  - matplotlib==3.9.2
  - mlxtend==0.23.1
  - numpy==1.26.4
  - optuna==3.6.1
  - packaging==24.1
  - pandas==2.2.2
  - psutil==6.0.0
  - pyarrow==15.0.2
  - pyyaml==6.0.2
  - scikit-learn==1.5.1
  - scipy==1.14.1
  - seaborn==0.13.2
  - statsmodels==0.14.2
  - xgboost==2.1.0
name: mlflow-env
